name: userservice
description: User Service GRPC Server
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.3 <3.0.0'


dev_dependencies:
  lints: ^1.0.0
  build_runner: ^2.1.4
  json_serializable: ^6.0.1
dependencies: 
  archive: ^3.1.6
  async: ^2.8.2
  fixnum: ^1.0.0
  grpc: ^3.0.2
  http2: ^2.0.0
  meta: ^1.7.0
  protobuf: ^2.0.0
  dgraph: 
    path: ../dgraph
  artemis: ^7.2.6-beta
  json_annotation: ^4.3.0
  equatable: ^2.0.3
  gql: ^0.13.1-alpha+1635149947792
  faker: ^2.0.0
  progressbar2: ^0.3.1
  
  
